from . import res_user_inherit
from . import res_company
from . import sem_department_inherit
from . import sem_employee_inherit
from . import hr_version_inherit
from . import res_group_inherit
from . import religion_category
from . import people_category
from . import cultural_level_category
from . import hr_job_inherit
from . import hr_department_job
from . import hr_employee_forecast_report
from . import sem_config_settings
from . import hr_job_transfer_wizard
from . import sem_work_location_inherit
from . import hr_employee_skill_inherit
